// Alchemy: reusable CuriOS media conversion service + application UI.
import {saveFile} from '../kernel/save.js';
import {h} from '../kernel/util.js';
import {V, remote, RUNNER} from '../kernel/vfs.js';
import {api} from '../kernel/runner.js';
import {win} from '../shell/wm.js';

export const isAlchemyImage=p=>/\.(png|jpe?g|webp|gif|bmp)$/i.test(p);
export const isAlchemyAudio=p=>/\.(mp3|wav|ogg|oga|m4a|aac|flac|opus)$/i.test(p);
export function alchemyFormats(p){const ext=(p.split('.').pop()||'').toLowerCase();const all=isAlchemyImage(p)?['png','jpg','webp']:isAlchemyAudio(p)?['mp3','wav','ogg','flac']:[];return all.filter(x=>!(x==='jpg'&&['jpg','jpeg'].includes(ext))&&x!==ext)}
const parent=p=>p.slice(0,p.lastIndexOf('/'))||'/', base=p=>p.split('/').pop(), stem=p=>base(p).replace(/\.[^.]+$/,'');
async function unique(dir,name){let p=(dir==='/'?'':dir)+'/'+name;if(!await V.stat(p))return p;const d=name.lastIndexOf('.'),a=d>0?name.slice(0,d):name,e=d>0?name.slice(d):'';for(let i=2;;i++){p=(dir==='/'?'':dir)+`/${a} (${i})${e}`;if(!await V.stat(p))return p}}
async function imageConvert(path,fmt){const blob=await V.blob(path),u=URL.createObjectURL(blob),im=new Image();im.src=u;await im.decode();const c=h('canvas',{width:im.naturalWidth,height:im.naturalHeight}),x=c.getContext('2d'),mime=fmt==='jpg'?'image/jpeg':'image/'+fmt;if(fmt==='jpg'){x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height)}x.drawImage(im,0,0);URL.revokeObjectURL(u);const out=await new Promise(r=>c.toBlob(r,mime,.9));if(!out)throw new Error(fmt.toUpperCase()+' export is not supported by this browser');const dest=await unique(parent(path),stem(path)+'.'+fmt);await V.put(dest,out);return dest}
const wav=b=>{const ch=b.numberOfChannels,n=b.length,sr=b.sampleRate,o=new DataView(new ArrayBuffer(44+n*ch*2)),S=(p,t)=>[...t].forEach((c,i)=>o.setUint8(p+i,c.charCodeAt(0)));S(0,'RIFF');o.setUint32(4,36+n*ch*2,true);S(8,'WAVEfmt ');o.setUint32(16,16,true);o.setUint16(20,1,true);o.setUint16(22,ch,true);o.setUint32(24,sr,true);o.setUint32(28,sr*ch*2,true);o.setUint16(32,ch*2,true);o.setUint16(34,16,true);S(36,'data');o.setUint32(40,n*ch*2,true);const cs=[...Array(ch).keys()].map(i=>b.getChannelData(i));let p=44;for(let i=0;i<n;i++)for(let c=0;c<ch;c++){const v=Math.max(-1,Math.min(1,cs[c][i]));o.setInt16(p,v<0?v*32768:v*32767,true);p+=2}return new Blob([o],{type:'audio/wav'})};
const lame=()=>window.lamejs?Promise.resolve():new Promise((ok,no)=>document.head.append(h('script',{src:'https://cdnjs.cloudflare.com/ajax/libs/lamejs/1.2.1/lame.min.js',onload:ok,onerror:()=>no(new Error('MP3 encoder could not be loaded'))})));
async function mp3(b){await lame();const ch=Math.min(2,b.numberOfChannels),enc=new lamejs.Mp3Encoder(ch,b.sampleRate,192),P=a=>Int16Array.from(a,v=>Math.max(-1,Math.min(1,v))*(v<0?32768:32767)),L=P(b.getChannelData(0)),R=ch>1?P(b.getChannelData(1)):null,out=[];for(let i=0;i<L.length;i+=1152){const d=ch>1?enc.encodeBuffer(L.subarray(i,i+1152),R.subarray(i,i+1152)):enc.encodeBuffer(L.subarray(i,i+1152));if(d.length)out.push(d)}const f=enc.flush();if(f.length)out.push(f);return new Blob(out,{type:'audio/mpeg'})}
async function browserAudio(path,fmt){if(!['mp3','wav'].includes(fmt))throw new Error(fmt.toUpperCase()+' conversion requires the CuriOS server with FFmpeg');const b=await V.blob(path),ctx=new(window.AudioContext||window.webkitAudioContext)();try{const a=await ctx.decodeAudioData(await b.arrayBuffer()),out=fmt==='mp3'?await mp3(a):wav(a),dest=await unique(parent(path),stem(path)+'.'+fmt);await V.put(dest,out);return dest}finally{ctx.close()}}
export async function convertPath(path,fmt){fmt=fmt.toLowerCase();let dest;if(isAlchemyImage(path))dest=await imageConvert(path,fmt);else if(isAlchemyAudio(path)){if(remote&&RUNNER){const r=await api('/api/alchemy',{method:'POST',body:JSON.stringify({path,format:fmt})});dest=(await r.json()).path}else dest=await browserAudio(path,fmt)}else throw new Error('Alchemy does not support this file type');window.dispatchEvent(new CustomEvent('curios:vfs-changed',{detail:{paths:[path,dest]}}));return dest}
export function alchemy(){win('alchemy','Alchemy',470,430,b=>{const fi=h('input',{type:'file',accept:'image/*,audio/*',style:'display:none'}),msg=h('div',{className:'msg'}),dz=h('div',{className:'dz',textContent:'Choose an image or audio file to transmute'});dz.onclick=()=>fi.click();fi.onchange=async()=>{const f=fi.files?.[0];if(!f)return;msg.textContent='Alchemy works directly on files stored in CuriOS. Import this file in Files, then right-click it → Alchemy for instant same-folder conversion.'};b.append(h('div',{className:'hd',textContent:'Alchemy'}),h('p',{textContent:'Format transmutation for images and audio. The fastest workflow is built directly into the Files context menu.'}),dz,fi,msg)})}
