// CuriOS dock: fixed system controls + persistent user app pins.
import {alchemy} from '../apps/alchemy.js';import {files} from '../apps/files.js';import {scribe} from '../apps/scribe.js';import {sam} from '../apps/sam.js';import {media} from '../apps/media.js';import {imageViewer} from '../apps/image-viewer.js';import {videoImporter} from '../apps/video-importer.js';import {settings} from '../apps/settings.js';import {vault} from '../apps/vault.js';import {photoAlbum} from '../apps/photo-album.js';
import {beep} from '../kernel/audio.js';import {dev} from '../kernel/device.js';import {set,sv} from '../kernel/state.js';import {$,h} from '../kernel/util.js';import {DEV} from '../kernel/vfs.js';import {S,show,wins} from './wm.js';import {lockSession,logoutSession} from './session.js';
const KEY='curios.dock.pins.v1',POS='curios.dock.launcherPosition.v1';
const apps={files:{name:'Files',open:files},media:{name:'Media',open:media},images:{name:'Images',open:imageViewer},videoimport:{name:'Video Importer',open:videoImporter},scribe:{name:'Scribe',open:()=>scribe('/Documents/untitled.scribe'),icon:'assets/apps/scribe.png'},sam:{name:'SAM',open:sam},alchemy:{name:'Alchemy',open:alchemy,icon:'assets/apps/alchemy.png'},photos:{name:'Photo Album',open:photoAlbum,icon:'assets/apps/photoalbum.png'},vault:{name:'Vault',open:vault,icon:'assets/apps/vault.png'},sys:{name:'Settings',open:settings,icon:'assets/apps/settings.png'}};
const I={menu:'<path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/>',vol:'<path d="M4 9h4l5-4v14l-5-4H4zM17 8c2 2 2 6 0 8"/>',session:'<path d="M12 3v9M7.2 5.8a8 8 0 1 0 9.6 0"/>'};
const pins=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'["files"]')}catch{return['files']}};const store=a=>localStorage.setItem(KEY,JSON.stringify(a));export const isDockPinned=id=>pins().includes(id);export function toggleDockPin(id){if(!apps[id]||id==='sys')return;let p=pins();p=p.includes(id)?p.filter(x=>x!==id):[...p,id];store(p);renderDock()}
function iconButton(id){const a=apps[id],b=h('button',{className:'dock-app',title:a.name,dataset:{app:id},onclick:()=>{if(wins[id])show(id);else a.open()}});if(a.icon)b.append(h('img',{src:a.icon,alt:''}));else b.textContent=a.name.slice(0,1);return b}
function renderDock(){const left=$('#dock-left'),right=$('#dock-right');if(!left||!right)return;const menu=h('button',{dataset:{a:'menu'},title:'Apps'});menu.innerHTML='<svg viewBox="0 0 24 24">'+I.menu+'</svg>';const user=h('div',{className:'dock-pins'},...pins().filter(x=>apps[x]).map(iconButton));const pos=localStorage.getItem(POS)||'left';left.replaceChildren(...(pos==='right'?[user,menu]:[menu,user]));const vol=h('button',{dataset:{a:'vol'},title:'Volume'}),session=h('button',{dataset:{a:'session'},title:'Lock / Log Out'});vol.innerHTML='<svg viewBox="0 0 24 24">'+I.vol+'</svg>';session.innerHTML='<svg viewBox="0 0 24 24">'+I.session+'</svg>';right.replaceChildren(vol,session)}
export const tick=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');let H=d.getHours();const s=set.h24?'':H>=12?' PM':' AM';if(!set.h24)H=H%12||12;$('#clk').textContent=`${p(H)}:${p(d.getMinutes())}:${p(d.getSeconds())}${s}`};tick();setInterval(tick,1000);renderDock();
const pop=$('#pop'),closePop=()=>pop.style.display='none';function popAt(btn,...c){const r=btn.getBoundingClientRect(),f=$('#fit').getBoundingClientRect();pop.replaceChildren(...c);pop.style.display='block';pop.style.left=Math.max(4,Math.min(1090,(r.left-f.left)/S-60))+'px'}
function appEntry(id){const a=apps[id],b=h('button',{className:'launcher-app',onclick(){closePop();a.open()},oncontextmenu:e=>{e.preventDefault();e.stopPropagation();if(id==='sys')return;popAt(b,h('div',{className:'hd',textContent:a.name}),h('button',{textContent:isDockPinned(id)?'Unpin from Dock':'Pin to Dock',onclick(){toggleDockPin(id);closePop()}}))}});if(a.icon)b.append(h('img',{className:'app-icon',src:a.icon,alt:''}));b.append(document.createTextNode(a.name));return b}
$('#dock').onclick=e=>{const b=e.target.closest('button[data-a]');if(!b)return;e.stopPropagation();const a=b.dataset.a;if(a==='menu'){const ids=['files','media','images','videoimport','scribe','sam','alchemy','photos','vault'];const run=Object.entries(wins).map(([id,w])=>h('button',{textContent:(w.e.style.display==='none'?'○ ':'● ')+w.t,onclick(){closePop();show(id)}}));popAt(b,...ids.map(appEntry),h('div',{className:'launcher-settings-divider'}),appEntry('sys'),...(run.length?[h('div',{className:'hd',textContent:'Running (○ = minimized)',style:'margin:8px 0 2px;padding:0 10px'}),...run]:[]))}else if(a==='session')popAt(b,h('div',{className:'hd',textContent:'Session'}),h('button',{textContent:'Lock',onclick(){closePop();lockSession()}}),h('button',{textContent:'Log Out',onclick(){closePop();logoutSession()}}));else if(a==='vol'){const m=h('input',{type:'checkbox',checked:!!set.mute,onchange(){set.mute=+m.checked;sv();if(DEV)dev('volume',set.mute?'mute':'unmute').catch(()=>0)}}),r=h('input',{type:'range',min:0,max:100,value:set.vol,style:'width:100%',oninput(){set.vol=+r.value;set.mute=0;m.checked=false;sv();if(DEV)dev('volume','set',set.vol).then(()=>dev('volume','unmute')).catch(()=>0)}});popAt(b,h('label',{className:'s'},'Volume',r),h('label',{className:'s'},'Mute',m),h('button',{textContent:'Test tone',onclick:beep}))}};
addEventListener('pointerdown',e=>{if(!e.target.closest('#pop,#dock'))closePop()});
